### ISSUE TITLE
Ambiguous error message

### ISSUE THREAD

**Issue by JoeyPetersen** [zalando/go-keyring#14]
Hi zalando,

I'm using the Arch Linux distribution and don't use a desktop environment, just a window manager (AwesomeWM). I ran into an issue when using a tool that included go-keyring where it was returning "ERROR: failed to unlock correct collection". I didn't know what specific collection it was referring to, so I had to trace it back to here and saw that you included the helpful information in your readme. I believe it would be better to include the name of the collection you are trying to unlock so if anyone runs into the same problem, they don't have to track it down.

Thanks,
Joey

**Comment by mikkeloscar** [comment]
@JoeyPetersen Thanks for the report. I'll look into it and see if we can add some more context to the error message.

I assume it worked after you added the correct collection?
