### ISSUE TITLE
Potentially collaborate?

### ISSUE THREAD

**Issue by lox** [zalando/go-keyring#19]
Hiya! We have recently extracted a very similar library out of https://github.com/99designs/aws-vault into https://github.com/99designs/keyring. 

We lack windows support, but we've got great macOS Keychain support. Any interest in perhaps collaborating and merging the two projects?

**Comment by szuecs** [comment]
Sounds good to me, and your macOS Keychain support looks much better than our shelling out approach. :)
Happy to get PR to change the macOS support or do you have another  idea in mind for collaboration (another org???)?
