### ISSUE TITLE
Stable API release

### ISSUE THREAD

**Issue by erdaltsksn** [zalando/go-keyring#49]
The version referenced in a go.mod is a pseudo-version based on the commit (v0.0.0-20200121091418-667557018717).

Pseudo-versions are a special type of pre-release version. Is it possible to release a stable API?

You can release v1.0.0 using git tags.

```sh
git tag v1.0.0
git push --tags
```

**NOTE:** In my projects, I prefer to use v0.1.0 as a initial version.

Reference: https://blog.golang.org/publishing-go-modules

**Comment by mikkeloscar** [comment]
@erdaltsksn This seems like a reasonable request. I would not release `v1.0.0` though since we have several issues/use cases reported which may require changing the API a bit. So to set expectations correctly I would also choose something like `v0.1.0` for now. @szuecs WDYT?

**Comment by szuecs** [comment]
@mikkeloscar yes `v0.1.0` sounds good

**Comment by mikkeloscar** [comment]
I have tagged the current master as [`v0.1.0`](https://github.com/zalando/go-keyring/releases/tag/v0.1.0)
