### ISSUE TITLE
Umlaut passwords fail to decode correctly on MacOS

### ISSUE THREAD

**Issue by allcloud-jonathan** [zalando/go-keyring#61]
https://github.com/zalando/go-keyring/pull/60 adds a test case for this. I'm unsure how this should be fixed correctly while maintaining the best possible backward compatibility. Options that came to mind:

- check for non-ascii characters and encode them all
- simply encode all passwords on MacOS

I happily implement but would request some guidance on which direction it should be.

**Comment by mikkeloscar** [comment]
> simply encode all passwords on MacOS

This seems to me the simplest solution. I would add some kind of prefix to the password e.g. `encoded:` such that you know whether to decode it or not when getting the password from the store. This would ensure that passwords stored before this change could still be read from the store without any issues (e.g. those would not be decoded).

**Comment by allcloud-jonathan** [comment]
The encoding on newline was already there. I just made it the default for all passwords and pushed the change to #60, which needs approval for the full tests to be run.

**Comment by allcloud-jonathan** [comment]
fixed in #60
