### ISSUE TITLE
Feature request: add FreeBSD support via GNOME keyring

### ISSUE THREAD

**Issue by torculus** [zalando/go-keyring#67]
Considering that FreeBSD has [go 1.17.5](https://www.freshports.org/lang/go/), [libsecret](https://www.freshports.org/security/libsecret), [gnome-keyring](https://www.freshports.org/security/gnome-keyring/), and [dbus-daemon](https://www.freebsd.org/cgi/man.cgi?query=dbus-daemon&sektion=1&apropos=0&manpath=FreeBSD+8.2-RELEASE+and+Ports), please consider adding support for FreeBSD

**Comment by szuecs** [comment]
@torculus can you test it?
Do you think we just need to create a build target?

**Comment by torculus** [comment]
Yeah, I'm willing to test it. I'm not much of a go programmer, but I think the Linux target should work well as a template

**Comment by szuecs** [comment]
@torculus can you try to build https://github.com/zalando/go-keyring/pull/68 on your system?
I just checked https://github.com/vmactions/freebsd-vm and it's a bit weird to run a VM inside macos and then I have to figure what ports I need to install (maybe you want to create a PR for the GH actions?).

**Comment by szuecs** [comment]
@torculus we merged the change and it should built also on *BSD.

**Comment by torculus** [comment]
So, I attempted to build on my machine and it's complaining about `u_int` and `uintptr_t` being invalid types

Long story short, upsteam `godbus` had an [issue](https://github.com/godbus/dbus/pull/208) with compiling on FreeBSD that was fixed back in 2020 (`godbus` version 5.0.4). Unfortunately, `go-keyring` is pulling `godbus` version 5.0.**_3_**, which is unpatched

I don't know if the requirement could be updated, but that would fix this issue

**Comment by mikkeloscar** [comment]
@torculus Could you try with this PR? https://github.com/zalando/go-keyring/pull/70

**Comment by twpayne** [comment]
Note that github.com/godbus/dbus currently does not compile on `freebsd/386`. See https://github.com/godbus/dbus/issues/315.

**Comment by twpayne** [comment]
Ah, so the problem is in fact that godbus/gobus relies on cgo and cgo is not easily available when cross-compiling. This may be tricky.

**Comment by mikkeloscar** [comment]
@torculus We have released version `v0.2.0` with the update you can try!

**Comment by mikkeloscar** [comment]
@twpayne From where do you cross-compile? Does it not work to compile directly on the target?

We were able to add a CI step running in freebsd VM which works: #71 (I don't know too many details about *BSD so maybe it's different from what you mean?)

**Comment by twpayne** [comment]
It does work when you compile directly, but I'm cross-compiling as I'm using [GoReleaser](https://goreleaser.com/) to build chezmoi's release binaries. The GoReleaser job runs on Linux (on GitHub Actions) and cross-compiles binaries for other operating systems and doesn't support cgo.

In practice I think zalando/go-keyring has done all that it's possible to reasonably do here. In chezmoi, I've used build tags to activate the GNOME Keyring functionality when it is available. https://github.com/twpayne/chezmoi/pull/1919 contains the gory details if you're interested.

**Comment by mikkeloscar** [comment]
Thanks for the information.

I will close this issue as it seems like we have done what we could from go-keyring side and support FreeBSD under the right conditions
